/**
 * Phase 5.6-A - opt-in backup git helpers + copy strategy.
 *
 * Everything in this module is conservative by design:
 *
 *   - `git` is invoked via `execFile` with `shell:false` and array args.
 *     No string interpolation into a shell. No environment leakage beyond
 *     `PATH`. Bounded timeout (15 s per call). Captured stdout/stderr are
 *     hard-capped at `MAX_OUTPUT_BYTES` so an unusually chatty git can't
 *     blow our event loop.
 *
 *   - The copy step is restricted to `agents/<slug>/memory/*.md`. The
 *     allowlist is on the destination side too: even if the source dir
 *     somehow contained sessions.db or a provider config, we'd refuse to
 *     write it into the backup repo. The `.gitignore` generator is a
 *     belt-and-braces second layer.
 *
 *   - `pushBackup` is only invoked when the caller explicitly sets
 *     `push:true` AND a remote is configured. There is no implicit push,
 *     no daemon, no schedule. The user is the trigger.
 *
 *   - Remote URLs are redacted before logging or echoing back to HTTP.
 *     A URL like `https://user:tok@github.com/...` is rewritten to
 *     `https://***@github.com/...` so the response can't expose a token
 *     the user accidentally embedded.
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import {
  mkdir,
  readdir,
  readFile,
  stat,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";

const execFileP = promisify(execFile);

const GIT_TIMEOUT_MS = 15_000;
const MAX_OUTPUT_BYTES = 1024 * 256; // 256 KB
const MAX_FILES_PER_RUN = 5000;
const MAX_FILE_BYTES = 4 * 1024 * 1024; // 4 MB per file

export class BackupGitError extends Error {
  readonly code:
    | "git_missing"
    | "git_failed"
    | "io_error"
    | "path_escapes_repo"
    | "too_many_files";
  constructor(code: BackupGitError["code"], message: string) {
    super(message);
    this.name = "BackupGitError";
    this.code = code;
  }
}

// ---------------------------------------------------------------------------
// .gitignore content (constant)
// ---------------------------------------------------------------------------

/**
 * The .gitignore the backup repo gets on first init. The list is
 * intentionally defensive: it excludes the obvious DB / log / secret
 * fingerprints even if the user later turns on `includeSessionsDb` or
 * the source dir somehow gains an unwanted file. The route layer + copy
 * filter also refuse those files independently.
 */
export const BACKUP_GITIGNORE = [
  "# CreativEdge backup .gitignore (Phase 5.6-A).",
  "# Generated by the backend; safe to edit but the backend will rewrite",
  "# the standard exclusions on every dry-run / run if this file is missing.",
  "",
  "# SQLite databases (sessions, fts shadow files, journals).",
  "sessions.db",
  "sessions.db-*",
  "*.db",
  "*.sqlite",
  "*.sqlite3",
  "",
  "# Logs.",
  "logs/",
  "*.log",
  "",
  "# Provider / runtime config (never committed).",
  "providers.json",
  "profile.json",
  "",
  "# Secrets and credentials (never committed).",
  ".env",
  ".env.*",
  "*.key",
  "*.pem",
  "",
].join("\n") + "\n";

export function buildBackupGitignore(): string {
  return BACKUP_GITIGNORE;
}

// ---------------------------------------------------------------------------
// Remote redaction
// ---------------------------------------------------------------------------

/**
 * Strip user:password from an https-style remote so we never echo a token
 * the user accidentally embedded in the URL. SSH-form remotes are returned
 * unchanged. Returns null when the input is null/empty.
 *
 *   https://user:tok@github.com/owner/repo.git
 *      -> https://***@github.com/owner/repo.git
 *   https://github.com/owner/repo.git -> unchanged
 *   git@github.com:owner/repo.git    -> unchanged
 */
export function redactRemote(remote: string | null | undefined): string | null {
  if (!remote || typeof remote !== "string") return null;
  return remote.replace(/^(https?:\/\/)[^/@\s]+@/, "$1***@");
}

// ---------------------------------------------------------------------------
// Git availability + low-level wrapper
// ---------------------------------------------------------------------------

export interface GitInvokeResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

async function runGit(args: string[], cwd: string): Promise<GitInvokeResult> {
  try {
    const r = await execFileP("git", args, {
      cwd,
      timeout: GIT_TIMEOUT_MS,
      maxBuffer: MAX_OUTPUT_BYTES,
      shell: false,
      windowsHide: true,
    });
    return {
      stdout: String(r.stdout ?? ""),
      stderr: String(r.stderr ?? ""),
      exitCode: 0,
    };
  } catch (err) {
    // execFile rejects on non-zero exit OR on spawn failure (ENOENT when
    // git isn't installed). Re-route both to typed errors so the caller
    // can give a useful HTTP response.
    const e = err as NodeJS.ErrnoException & {
      stdout?: unknown;
      stderr?: unknown;
      code?: string | number;
    };
    if (e.code === "ENOENT") {
      throw new BackupGitError("git_missing", "git is not installed or not on PATH");
    }
    const stdout =
      typeof e.stdout === "string"
        ? e.stdout
        : Buffer.isBuffer(e.stdout)
          ? e.stdout.toString("utf-8")
          : "";
    const stderr =
      typeof e.stderr === "string"
        ? e.stderr
        : Buffer.isBuffer(e.stderr)
          ? e.stderr.toString("utf-8")
          : "";
    const exitCode = typeof e.code === "number" ? e.code : -1;
    return { stdout, stderr, exitCode };
  }
}

export async function gitAvailable(): Promise<boolean> {
  try {
    const r = await runGit(["--version"], process.cwd());
    return r.exitCode === 0 && /^git version /.test(r.stdout);
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Repo init + status + commit + push
// ---------------------------------------------------------------------------

export async function ensureBackupRepo(repoDir: string): Promise<{ created: boolean }> {
  await mkdir(repoDir, { recursive: true });
  // Is this already a git repo?
  const gitDir = join(repoDir, ".git");
  let alreadyRepo = false;
  try {
    const s = await stat(gitDir);
    alreadyRepo = s.isDirectory();
  } catch {
    alreadyRepo = false;
  }
  if (alreadyRepo) return { created: false };

  const r = await runGit(["init", "--initial-branch=main"], repoDir);
  if (r.exitCode !== 0) {
    // Older git installs don't support --initial-branch; retry without it.
    const r2 = await runGit(["init"], repoDir);
    if (r2.exitCode !== 0) {
      throw new BackupGitError(
        "git_failed",
        "git init failed: " + (r2.stderr || r.stderr || "unknown").slice(0, 400)
      );
    }
  }
  // Give the new repo a sensible identity so commits don't fail later. We
  // use repo-local config (not --global) so we don't touch user-wide state.
  await runGit(["config", "user.email", "creativedge-backup@localhost"], repoDir);
  await runGit(["config", "user.name", "CreativEdge Backup"], repoDir);
  return { created: true };
}

/**
 * Write or refresh the .gitignore in the backup repo. Idempotent: if the
 * file already exists and matches `BACKUP_GITIGNORE` byte-for-byte, skip
 * the write. Otherwise write to a `.tmp` and rename.
 */
export async function writeBackupGitignore(
  repoDir: string
): Promise<{ wrote: boolean }> {
  const path = join(repoDir, ".gitignore");
  let existing = "";
  try {
    existing = await readFile(path, "utf-8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException)?.code !== "ENOENT") {
      throw new BackupGitError(
        "io_error",
        "failed to read .gitignore: " + (err as Error)?.message
      );
    }
  }
  if (existing === BACKUP_GITIGNORE) return { wrote: false };
  await mkdir(repoDir, { recursive: true });
  await writeFile(path, BACKUP_GITIGNORE, { encoding: "utf-8" });
  return { wrote: true };
}

// ---------------------------------------------------------------------------
// Selective copy: agents/<slug>/memory/*.md only
// ---------------------------------------------------------------------------

const MEMORY_FILE_RE = /\.md$/i;
const ALLOWED_MEMORY_BASENAMES = new Set([
  "core_memory.md",
  "episodic_memory.md",
  // Optional README the user may keep alongside; allowed because it can't
  // expose anything not already in the runtime source.
  "README.md",
  "readme.md",
]);

export interface CopyResult {
  filesConsidered: number;
  filesCopied: number;
  filesSkipped: string[];
}

/**
 * Selectively mirror `<sourceDir>/<slug>/memory/*.md` into
 * `<repoDir>/agents/<slug>/memory/<file>.md`. The repo's `agents/` prefix
 * mirrors the source layout under the runtime root so a future restore
 * tool can reverse the operation by copying back.
 *
 * Filter rules:
 *   - Only `*.md` files inside a `<slug>/memory/` directory are considered.
 *   - Basename allowlist: `core_memory.md`, `episodic_memory.md`,
 *     `README.md` / `readme.md`. Anything else is skipped (and reported
 *     in `filesSkipped`).
 *   - `*.lock` / `*.tmp` are skipped explicitly.
 *   - Files > 4 MB are skipped (they're almost certainly the wrong file).
 *   - The slug directory name must match SLUG_RE used elsewhere; otherwise
 *     skipped.
 *
 * Path-safety: every resolved destination path must stay inside `repoDir`.
 */
const SLUG_RE = /^[a-z][a-z0-9-]{1,40}$/;

export async function syncAgentsToBackupRepo(
  sourceDir: string,
  repoDir: string
): Promise<CopyResult> {
  const considered: string[] = [];
  const skipped: string[] = [];
  let copied = 0;

  let slugEntries: string[];
  try {
    slugEntries = await readdir(sourceDir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException)?.code === "ENOENT") {
      return { filesConsidered: 0, filesCopied: 0, filesSkipped: [] };
    }
    throw new BackupGitError(
      "io_error",
      "failed to list agents source dir: " + (err as Error)?.message
    );
  }

  const resolvedRepo = resolve(repoDir);
  const repoPrefix = resolvedRepo.endsWith(sep) ? resolvedRepo : resolvedRepo + sep;

  for (const slug of slugEntries) {
    if (!SLUG_RE.test(slug)) {
      skipped.push(`<sourceDir>/${slug}  (slug regex)`);
      continue;
    }
    const memDir = join(sourceDir, slug, "memory");
    let memFiles: string[];
    try {
      memFiles = await readdir(memDir);
    } catch {
      // No memory dir for this slug yet; not an error.
      continue;
    }

    for (const name of memFiles) {
      considered.push(`${slug}/memory/${name}`);
      if (considered.length > MAX_FILES_PER_RUN) {
        throw new BackupGitError(
          "too_many_files",
          `more than ${MAX_FILES_PER_RUN} candidate files; aborting for safety`
        );
      }
      if (name.endsWith(".lock") || name.endsWith(".tmp")) {
        skipped.push(`${slug}/memory/${name}  (lock/tmp)`);
        continue;
      }
      if (!MEMORY_FILE_RE.test(name)) {
        skipped.push(`${slug}/memory/${name}  (non-md)`);
        continue;
      }
      if (!ALLOWED_MEMORY_BASENAMES.has(name)) {
        skipped.push(`${slug}/memory/${name}  (basename not allowlisted)`);
        continue;
      }
      const srcPath = join(memDir, name);
      let s;
      try {
        s = await stat(srcPath);
      } catch {
        skipped.push(`${slug}/memory/${name}  (stat failed)`);
        continue;
      }
      if (!s.isFile()) {
        skipped.push(`${slug}/memory/${name}  (not a regular file)`);
        continue;
      }
      if (s.size > MAX_FILE_BYTES) {
        skipped.push(`${slug}/memory/${name}  (>${MAX_FILE_BYTES} bytes)`);
        continue;
      }
      const destPath = join(resolvedRepo, "agents", slug, "memory", name);
      const resolvedDest = resolve(destPath);
      if (resolvedDest !== resolvedRepo && !resolvedDest.startsWith(repoPrefix)) {
        throw new BackupGitError(
          "path_escapes_repo",
          `destination path escapes backup repo: ${resolvedDest}`
        );
      }
      const buf = await readFile(srcPath);
      await mkdir(dirname(destPath), { recursive: true });
      await writeFile(destPath, buf);
      copied++;
    }
  }

  return {
    filesConsidered: considered.length,
    filesCopied: copied,
    filesSkipped: skipped,
  };
}

// ---------------------------------------------------------------------------
// Status + commit + push
// ---------------------------------------------------------------------------

export interface StatusSummary {
  added: number;
  modified: number;
  deleted: number;
  untracked: number;
  /** True iff at least one of added/modified/deleted/untracked is > 0. */
  changed: boolean;
}

/**
 * Parse `git status --porcelain=v1 -z` output into a tiny summary. The
 * `-z` form NUL-separates entries so filenames with whitespace or
 * newlines can't confuse the parser.
 *
 * Status codes (see git-status(1)):
 *   "M " / " M" / "MM" -> modified
 *   "A " / " A"        -> added
 *   "D " / " D"        -> deleted
 *   "??"               -> untracked
 *   "R "               -> renamed (counted as modified)
 *   anything else      -> ignored
 */
export function parseStatusPorcelain(raw: string): StatusSummary {
  let added = 0,
    modified = 0,
    deleted = 0,
    untracked = 0;
  if (!raw) {
    return { added, modified, deleted, untracked, changed: false };
  }
  const entries = raw.split("\0").filter((s) => s.length > 0);
  for (const entry of entries) {
    if (entry.length < 3) continue;
    const code = entry.slice(0, 2);
    if (code === "??") {
      untracked++;
    } else if (code.includes("A")) {
      added++;
    } else if (code.includes("D")) {
      deleted++;
    } else if (code.includes("M") || code.includes("R")) {
      modified++;
    }
  }
  return {
    added,
    modified,
    deleted,
    untracked,
    changed: added + modified + deleted + untracked > 0,
  };
}

export async function getGitStatus(repoDir: string): Promise<StatusSummary> {
  const r = await runGit(["status", "--porcelain=v1", "-z"], repoDir);
  if (r.exitCode !== 0) {
    throw new BackupGitError(
      "git_failed",
      "git status failed: " + (r.stderr || "unknown").slice(0, 400)
    );
  }
  return parseStatusPorcelain(r.stdout);
}

export interface CommitResult {
  committed: boolean;
  hash: string | null;
  message: string;
}

/**
 * Stage the `agents/` subtree + the `.gitignore`, then commit if there is
 * anything to commit. The two file scopes are explicit on purpose so the
 * commit can never accidentally pick up an unexpected sibling file that
 * appeared in the repo dir.
 *
 * Returns `{committed:false, hash:null}` when the working tree is clean.
 */
export async function commitBackup(
  repoDir: string,
  message: string
): Promise<CommitResult> {
  // Stage only the paths we control. Each pathspec is added independently
  // so a missing `agents/` directory (e.g. a fresh repo with just the
  // .gitignore) doesn't fail the whole commit. `git add` exits non-zero
  // when the pathspec doesn't match anything, so we check existence first.
  const pathsToStage: string[] = [];
  try {
    await stat(join(repoDir, "agents"));
    pathsToStage.push("agents");
  } catch {
    // agents/ doesn't exist yet; nothing to stage on this path.
  }
  try {
    await stat(join(repoDir, ".gitignore"));
    pathsToStage.push(".gitignore");
  } catch {
    // No .gitignore yet (unusual but not fatal).
  }
  if (pathsToStage.length > 0) {
    const stageResult = await runGit(["add", "--", ...pathsToStage], repoDir);
    if (stageResult.exitCode !== 0) {
      throw new BackupGitError(
        "git_failed",
        "git add failed: " + (stageResult.stderr || "unknown").slice(0, 400)
      );
    }
  }
  // Anything to commit?
  const diffCheck = await runGit(["diff", "--cached", "--quiet"], repoDir);
  if (diffCheck.exitCode === 0) {
    return { committed: false, hash: null, message };
  }
  const commit = await runGit(["commit", "-m", message], repoDir);
  if (commit.exitCode !== 0) {
    throw new BackupGitError(
      "git_failed",
      "git commit failed: " + (commit.stderr || "unknown").slice(0, 400)
    );
  }
  const sha = await runGit(["rev-parse", "HEAD"], repoDir);
  const hash = sha.exitCode === 0 ? sha.stdout.trim() : null;
  return { committed: true, hash, message };
}

export interface PushResult {
  pushed: boolean;
  reason?: string;
}

/**
 * Push to `origin/main`. Only call when:
 *   - the user explicitly set `push:true` in the request body
 *   - the config has a non-null remote
 *   - the local repo's `origin` remote is already configured by the user
 *
 * No credential probing, no token storage, no API calls. If the local
 * remote isn't set up the push will fail and we return the redacted git
 * error - the user is expected to run `git remote add origin <url>` once.
 */
export async function pushBackup(repoDir: string): Promise<PushResult> {
  const remoteCheck = await runGit(["remote"], repoDir);
  const remotes = remoteCheck.stdout
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);
  if (!remotes.includes("origin")) {
    return {
      pushed: false,
      reason:
        "origin remote not configured; run `git remote add origin <url>` in " +
        repoDir,
    };
  }
  const r = await runGit(["push", "origin", "HEAD"], repoDir);
  if (r.exitCode !== 0) {
    return {
      pushed: false,
      reason: "git push failed: " + (r.stderr || "unknown").slice(0, 400),
    };
  }
  return { pushed: true };
}

// ---------------------------------------------------------------------------
// Helpers used by the route
// ---------------------------------------------------------------------------

/** Returns true iff `repoDir/.git/` exists. Read-only; never modifies state. */
export async function isBackupRepoInitialized(repoDir: string): Promise<boolean> {
  try {
    const s = await stat(join(repoDir, ".git"));
    return s.isDirectory();
  } catch {
    return false;
  }
}

/** Returns true iff `repoDir` has an `origin` remote configured. */
export async function hasOriginRemote(repoDir: string): Promise<boolean> {
  try {
    const r = await runGit(["remote"], repoDir);
    return r.stdout
      .split("\n")
      .map((s) => s.trim())
      .includes("origin");
  } catch {
    return false;
  }
}
